[variables]
GO_VERSION = "1.21"

[phases.setup]
nixPkgs = ["go_1_21"]

[phases.build]
dependsOn = ["setup"]
cmds = [
  "cd backend",
  "go mod download",
  "go build -o main ."
]

[start]
cmd = "cd backend && ./main"
EOF