# --- Stage 1: Build ---
FROM golang:1.23 AS builder

WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -o main .

# --- Stage 2: Runtime ---
FROM alpine

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 3000
CMD ["./main"]