# --- Stage 1: Build ---
    FROM golang:1.23-alpine AS builder

    RUN apk add --no-cache gcc musl-dev
    
    WORKDIR /app
    COPY . .
    
    ENV CGO_ENABLED=1
    ENV GOOS=linux
    ENV GOARCH=amd64
    
    RUN go mod tidy
    RUN go build -o main .
    
    # --- Stage 2: Runtime ---
    FROM alpine:latest
    
    RUN apk add --no-cache libsqlite3
    
    WORKDIR /app
    
    COPY --from=builder /app/main .
    
    EXPOSE 3000
    
    CMD ["./main"]
    