package models

type PlayerMatchStats struct {
    MatchID                    float64
    PlayerID                   float64
    TotalPass                  float64
    AccuratePass               float64
    TotalLongBalls             float64
    AccurateLongBalls          float64
    GoalAssist                 float64
    SavedShotsFromInsideTheBox float64
    Saves                      float64
    MinutesPlayed              float64
    Touches                    float64
    Rating                     float64
    PossessionLostCtrl         float64
    KeyPass                    float64
    GoalsPrevented             float64
    AerialWon                  float64
    DuelLost                   float64
    DuelWon                    float64
    OnTargetScoringAttempt     float64
    Goals                      float64
    TotalClearance             float64
    InterceptionWon            float64
    TotalTackle                float64
    WasFouled                  float64
    Fouls                      float64
    ExpectedGoals              float64
    ExpectedAssists            float64
    AerialLost                 float64
    ChallengeLost              float64
    TotalCross                 float64
    TotalContest               float64
    WonContest                 float64
    OutfielderBlock            float64
    BigChanceCreated           float64
    Dispossessed               float64
    ShotOffTarget              float64
    AccurateCross              float64
    TotalOffside               float64
    BlockedScoringAttempt      float64
    PenaltyWon                 float64
    PenaltyConceded            float64
    BigChanceMissed            float64
    TotalKeeperSweeper         float64
    AccurateKeeperSweeper      float64
    GoodHighClaim              float64
    Punches                    float64
    ClearanceOffLine           float64
    HitWoodwork                float64
    ErrorLeadToAShot           float64
    OwnGoals                   float64
    LastManTackle              float64
    ErrorLeadToAGoal           float64
    PenaltySave                float64
    PenaltyMiss                float64
}
