package models

type PlayerMatchStat struct {
	MatchID                    int      `json:"matchID"`
	PlayerID                   int      `json:"playerID"`
	TotalPass                  *float64 `json:"totalPass"`
	AccuratePass               *float64 `json:"accuratePass"`
	TotalLongBalls             *float64 `json:"totalLongBalls"`
	AccurateLongBalls          *float64 `json:"accurateLongBalls"`
	GoalAssist                 *float64 `json:"goalAssist"`
	SavedShotsFromInsideTheBox *float64 `json:"savedShotsFromInsideTheBox"`
	Saves                      *float64 `json:"saves"`
	MinutesPlayed              *float64 `json:"minutesPlayed"`
	Touches                    *float64 `json:"touches"`
	Rating                     *float64 `json:"rating"`
	PossessionLostCtrl         *float64 `json:"possessionLostCtrl"`
	KeyPass                    *float64 `json:"keyPass"`
	GoalsPrevented             *float64 `json:"goalsPrevented"`
	AerialWon                  *float64 `json:"aerialWon"`
	DuelLost                   *float64 `json:"duelLost"`
	DuelWon                    *float64 `json:"duelWon"`
	OnTargetScoringAttempt     *float64 `json:"onTargetScoringAttempt"`
	Goals                      *float64 `json:"goals"`
	TotalClearance             *float64 `json:"totalClearance"`
	InterceptionWon            *float64 `json:"interceptionWon"`
	TotalTackle                *float64 `json:"totalTackle"`
	WasFouled                  *float64 `json:"wasFouled"`
	Fouls                      *float64 `json:"fouls"`
	ExpectedGoals              *float64 `json:"expectedGoals"`
	ExpectedAssists            *float64 `json:"expectedAssists"`
	AerialLost                 *float64 `json:"aerialLost"`
	ChallengeLost              *float64 `json:"challengeLost"`
	TotalCross                 *float64 `json:"totalCross"`
	TotalContest               *float64 `json:"totalContest"`
	WonContest                 *float64 `json:"wonContest"`
	OutfielderBlock            *float64 `json:"outfielderBlock"`
	BigChanceCreated           *float64 `json:"bigChanceCreated"`
	Dispossessed               *float64 `json:"dispossessed"`
	ShotOffTarget              *float64 `json:"shotOffTarget"`
	AccurateCross              *float64 `json:"accurateCross"`
	TotalOffside               *float64 `json:"totalOffside"`
	BlockedScoringAttempt      *float64 `json:"blockedScoringAttempt"`
	PenaltyWon                 *float64 `json:"penaltyWon"`
	PenaltyConceded            *float64 `json:"penaltyConceded"`
	BigChanceMissed            *float64 `json:"bigChanceMissed"`
	TotalKeeperSweeper         *float64 `json:"totalKeeperSweeper"`
	AccurateKeeperSweeper      *float64 `json:"accurateKeeperSweeper"`
	GoodHighClaim              *float64 `json:"goodHighClaim"`
	Punches                    *float64 `json:"punches"`
	ClearanceOffLine           *float64 `json:"clearanceOffLine"`
	HitWoodwork                *float64 `json:"hitWoodwork"`
	ErrorLeadToAShot           *float64 `json:"errorLeadToAShot"`
	OwnGoals                   *float64 `json:"ownGoals"`
	LastManTackle              *float64 `json:"lastManTackle"`
	ErrorLeadToAGoal           *float64 `json:"errorLeadToAGoal"`
	PenaltySave                *float64 `json:"penaltySave"`
	PenaltyMiss                *float64 `json:"penaltyMiss"`
}
