package models

import "database/sql"

type PlayerMatchStat struct {
    MatchID                    int
    PlayerID                   int
    TotalPass                  sql.NullFloat64
    AccuratePass               sql.NullFloat64
    TotalLongBalls             sql.NullFloat64
    AccurateLongBalls          sql.NullFloat64
    GoalAssist                 sql.NullFloat64
    SavedShotsFromInsideTheBox sql.NullFloat64
    Saves                      sql.NullFloat64
    MinutesPlayed              sql.NullFloat64
    Touches                    sql.NullFloat64
    Rating                     sql.NullFloat64
    PossessionLostCtrl         sql.NullFloat64
    KeyPass                    sql.NullFloat64
    GoalsPrevented             sql.NullFloat64
    AerialWon                  sql.NullFloat64
    DuelLost                   sql.NullFloat64
    DuelWon                    sql.NullFloat64
    OnTargetScoringAttempt     sql.NullFloat64
    Goals                      sql.NullFloat64
    TotalClearance             sql.NullFloat64
    InterceptionWon            sql.NullFloat64
    TotalTackle                sql.NullFloat64
    WasFouled                  sql.NullFloat64
    Fouls                      sql.NullFloat64
    ExpectedGoals              sql.NullFloat64
    ExpectedAssists            sql.NullFloat64
    AerialLost                 sql.NullFloat64
    ChallengeLost              sql.NullFloat64
    TotalCross                 sql.NullFloat64
    TotalContest               sql.NullFloat64
    WonContest                 sql.NullFloat64
    OutfielderBlock            sql.NullFloat64
    BigChanceCreated           sql.NullFloat64
    Dispossessed               sql.NullFloat64
    ShotOffTarget              sql.NullFloat64
    AccurateCross              sql.NullFloat64
    TotalOffside               sql.NullFloat64
    BlockedScoringAttempt      sql.NullFloat64
    PenaltyWon                 sql.NullFloat64
    PenaltyConceded            sql.NullFloat64
    BigChanceMissed            sql.NullFloat64
    TotalKeeperSweeper         sql.NullFloat64
    AccurateKeeperSweeper      sql.NullFloat64
    GoodHighClaim              sql.NullFloat64
    Punches                    sql.NullFloat64
    ClearanceOffLine           sql.NullFloat64
    HitWoodwork                sql.NullFloat64
    ErrorLeadToAShot           sql.NullFloat64
    OwnGoals                   sql.NullFloat64
    LastManTackle              sql.NullFloat64
    ErrorLeadToAGoal           sql.NullFloat64
    PenaltySave                sql.NullFloat64
    PenaltyMiss                sql.NullFloat64
}
