package models

import "database/sql"

type TeamSeasonStat struct {
    UniqueTournamentID          int
    SeasonID                   int
    TeamID                     int
    AccurateLongBalls          sql.NullFloat64
    AccurateLongBallsPercentage sql.NullFloat64
    AccuratePasses             sql.NullFloat64
    AccuratePassesPercentage   sql.NullFloat64
    AerialDuelsWon             sql.NullFloat64
    Assists                    sql.NullFloat64
    BigChancesCreated          sql.NullFloat64
    BigChancesMissed           sql.NullFloat64
    CleanSheet                 sql.NullFloat64
    DribbledPast               sql.NullFloat64
    ErrorLeadToGoal            sql.NullFloat64
    ExpectedAssists            sql.NullFloat64
    ExpectedGoals              sql.NullFloat64
    Goals                      sql.NullFloat64
    GoalsAssistsSum            sql.NullFloat64
    GoalsConceded              sql.NullFloat64
    GoalsPrevented             sql.NullFloat64
    Interceptions              sql.NullFloat64
    KeyPasses                  sql.NullFloat64
    MinutesPlayed              sql.NullFloat64
    PassToAssist               sql.NullFloat64
    PenaltyFaced               sql.NullFloat64
    PenaltySave                sql.NullFloat64
    Rating                     sql.NullFloat64
    RedCards                   sql.NullFloat64
    SavedShotsFromInsideTheBox sql.NullFloat64
    Saves                      sql.NullFloat64
    SuccessfulDribbles         sql.NullFloat64
    Tackles                    sql.NullFloat64
    YellowCards                sql.NullFloat64
    TotalRating                sql.NullFloat64
    CountRating                sql.NullFloat64
    TotalLongBalls             sql.NullFloat64
    TotalPasses                sql.NullFloat64
    ShotsFromInsideTheBox      sql.NullFloat64
    Appearances                sql.NullFloat64
    Type                       sql.NullFloat64
    ID                         int
    AccurateCrosses            sql.NullFloat64
    AccurateCrossesPercentage  sql.NullFloat64
    BlockedShots               sql.NullFloat64
    ShotsOnTarget              sql.NullFloat64
    TotalShots                 sql.NullFloat64
    TotalCross                 sql.NullFloat64
}
