package models

import "database/sql"

type TeamMatchStat struct {
    MatchID              int
    TeamID               int
    BallPossession       sql.NullFloat64
    ExpectedGoals        sql.NullFloat64
    BigChances           sql.NullFloat64
    TotalShots           sql.NullFloat64
    GoalkeeperSaves      sql.NullFloat64
    CornerKicks          sql.NullFloat64
    Fouls                sql.NullFloat64
    Passes               sql.NullFloat64
    Tackles              sql.NullFloat64
    FreeKicks            sql.NullFloat64
    YellowCards          sql.NullFloat64
    RedCards             sql.NullFloat64
    ShotsOnTarget        sql.NullFloat64
    HitWoodwork          sql.NullFloat64
    ShotsOffTarget       sql.NullFloat64
    BlockedShots         sql.NullFloat64
    ShotsInsideBox       sql.NullFloat64
    ShotsOutsideBox      sql.NullFloat64
    BigChancesScored     sql.NullFloat64
    BigChancesMissed     sql.NullFloat64
    ThroughBalls         sql.NullFloat64
    TouchesInPenaltyArea sql.NullFloat64
    FouledInFinalThird   sql.NullFloat64
    Offsides             sql.NullFloat64
    AccuratePasses       sql.NullFloat64
    ThrowIns             sql.NullFloat64
    FinalThirdEntries    sql.NullFloat64
    FinalThirdPhase      sql.NullFloat64
    LongBalls            sql.NullFloat64
    Crosses              sql.NullFloat64
    Duels                sql.NullFloat64
    Dispossessed         sql.NullFloat64
    GroundDuels          sql.NullFloat64
    AerialDuels          sql.NullFloat64
    Dribbles             sql.NullFloat64
    TacklesWon           sql.NullFloat64
    TotalTackles         sql.NullFloat64
    Interceptions        sql.NullFloat64
    Recoveries           sql.NullFloat64
    Clearances           sql.NullFloat64
    TotalSaves           sql.NullFloat64
    GoalsPrevented       sql.NullFloat64
    GoalKicks            sql.NullFloat64
    BigSaves             sql.NullFloat64
    HighClaims           sql.NullFloat64
    Punches              sql.NullFloat64
    ErrorsLeadToAShot    sql.NullFloat64
    ErrorsLeadToAGoal    sql.NullFloat64
    PenaltySaves         sql.NullFloat64
}
