package models

type TeamSeasonStat struct {
    ID                               int     `json:"id"`
    TeamID                           int     `json:"teamId"`
    UniqueTournamentID               int     `json:"uniqueTournamentId"`
    SeasonID                        int     `json:"seasonId"`
    
    GoalsScored                     int     `json:"goalsScored"`
    GoalsConceded                   int     `json:"goalsConceded"`
    OwnGoals                       int     `json:"ownGoals"`
    Assists                        int     `json:"assists"`
    Shots                         int     `json:"shots"`
    PenaltyGoals                  int     `json:"penaltyGoals"`
    PenaltiesTaken                int     `json:"penaltiesTaken"`
    FreeKickGoals                 int     `json:"freeKickGoals"`
    FreeKickShots                int     `json:"freeKickShots"`
    GoalsFromInsideTheBox        int     `json:"goalsFromInsideTheBox"`
    GoalsFromOutsideTheBox       int     `json:"goalsFromOutsideTheBox"`
    ShotsFromInsideTheBox        int     `json:"shotsFromInsideTheBox"`
    ShotsFromOutsideTheBox       int     `json:"shotsFromOutsideTheBox"`
    HeadedGoals                  int     `json:"headedGoals"`
    LeftFootGoals                int     `json:"leftFootGoals"`
    RightFootGoals               int     `json:"rightFootGoals"`
    BigChances                   int     `json:"bigChances"`
    BigChancesCreated            int     `json:"bigChancesCreated"`
    BigChancesMissed             int     `json:"bigChancesMissed"`
    ShotsOnTarget                int     `json:"shotsOnTarget"`
    ShotsOffTarget               int     `json:"shotsOffTarget"`
    BlockedScoringAttempt        int     `json:"blockedScoringAttempt"`
    SuccessfulDribbles           int     `json:"successfulDribbles"`
    DribbleAttempts              int     `json:"dribbleAttempts"`
    Corners                      int     `json:"corners"`
    HitWoodwork                  int     `json:"hitWoodwork"`
    FastBreaks                   int     `json:"fastBreaks"`
    FastBreakGoals               int     `json:"fastBreakGoals"`
    FastBreakShots               int     `json:"fastBreakShots"`
    AverageBallPossession        float64 `json:"averageBallPossession"`
    TotalPasses                 int     `json:"totalPasses"`
    AccuratePasses              int     `json:"accuratePasses"`
    AccuratePassesPercentage    float64 `json:"accuratePassesPercentage"`
    TotalOwnHalfPasses          int     `json:"totalOwnHalfPasses"`
    AccurateOwnHalfPasses       int     `json:"accurateOwnHalfPasses"`
    AccurateOwnHalfPassesPercentage float64 `json:"accurateOwnHalfPassesPercentage"`
    TotalOppositionHalfPasses   int     `json:"totalOppositionHalfPasses"`
    AccurateOppositionHalfPasses int    `json:"accurateOppositionHalfPasses"`
    AccurateOppositionHalfPassesPercentage float64 `json:"accurateOppositionHalfPassesPercentage"`
    TotalLongBalls              int     `json:"totalLongBalls"`
    AccurateLongBalls           int     `json:"accurateLongBalls"`
    AccurateLongBallsPercentage float64 `json:"accurateLongBallsPercentage"`
    TotalCrosses                int     `json:"totalCrosses"`
    AccurateCrosses             int     `json:"accurateCrosses"`
    AccurateCrossesPercentage   float64 `json:"accurateCrossesPercentage"`
    CleanSheets                 int     `json:"cleanSheets"`
    Tackles                     int     `json:"tackles"`
    Interceptions               int     `json:"interceptions"`
    Saves                       int     `json:"saves"`
    ErrorsLeadingToGoal         int     `json:"errorsLeadingToGoal"`
    ErrorsLeadingToShot         int     `json:"errorsLeadingToShot"`
    PenaltiesCommitted          int     `json:"penaltiesCommitted"`
    PenaltyGoalsConceded        int     `json:"penaltyGoalsConceded"`
    Clearances                  int     `json:"clearances"`
    ClearancesOffLine           int     `json:"clearancesOffLine"`
    LastManTackles              int     `json:"lastManTackles"`
    TotalDuels                  int     `json:"totalDuels"`
    DuelsWon                   int     `json:"duelsWon"`
    DuelsWonPercentage          float64 `json:"duelsWonPercentage"`
    TotalGroundDuels            int     `json:"totalGroundDuels"`
    GroundDuelsWon             int     `json:"groundDuelsWon"`
    GroundDuelsWonPercentage    float64 `json:"groundDuelsWonPercentage"`
    TotalAerialDuels            int     `json:"totalAerialDuels"`
    AerialDuelsWon             int     `json:"aerialDuelsWon"`
    AerialDuelsWonPercentage    float64 `json:"aerialDuelsWonPercentage"`
    PossessionLost              int     `json:"possessionLost"`
    Offsides                    int     `json:"offsides"`
    Fouls                       int     `json:"fouls"`
    YellowCards                 int     `json:"yellowCards"`
    YellowRedCards              int     `json:"yellowRedCards"`
    RedCards                    int     `json:"redCards"`
    AvgRating                   float64 `json:"avgRating"`
    AccurateFinalThirdPassesAgainst int  `json:"accurateFinalThirdPassesAgainst"`
    AccurateOppositionHalfPassesAgainst int `json:"accurateOppositionHalfPassesAgainst"`
    AccurateOwnHalfPassesAgainst int    `json:"accurateOwnHalfPassesAgainst"`
    AccuratePassesAgainst       int     `json:"accuratePassesAgainst"`
    BigChancesAgainst           int     `json:"bigChancesAgainst"`
    BigChancesCreatedAgainst    int     `json:"bigChancesCreatedAgainst"`
    BigChancesMissedAgainst     int     `json:"bigChancesMissedAgainst"`
    ClearancesAgainst           int     `json:"clearancesAgainst"`
    CornersAgainst              int     `json:"cornersAgainst"`
    CrossesSuccessfulAgainst    int     `json:"crossesSuccessfulAgainst"`
    CrossesTotalAgainst         int     `json:"crossesTotalAgainst"`
    DribbleAttemptsTotalAgainst int     `json:"dribbleAttemptsTotalAgainst"`
    DribbleAttemptsWonAgainst   int     `json:"dribbleAttemptsWonAgainst"`
    ErrorsLeadingToGoalAgainst  int     `json:"errorsLeadingToGoalAgainst"`
    ErrorsLeadingToShotAgainst  int     `json:"errorsLeadingToShotAgainst"`
    HitWoodworkAgainst          int     `json:"hitWoodworkAgainst"`
    InterceptionsAgainst        int     `json:"interceptionsAgainst"`
    KeyPassesAgainst            int     `json:"keyPassesAgainst"`
    LongBallsSuccessfulAgainst  int     `json:"longBallsSuccessfulAgainst"`
    LongBallsTotalAgainst       int     `json:"longBallsTotalAgainst"`
    OffsidesAgainst             int     `json:"offsidesAgainst"`
    RedCardsAgainst             int     `json:"redCardsAgainst"`
    ShotsAgainst                int     `json:"shotsAgainst"`
    ShotsBlockedAgainst         int     `json:"shotsBlockedAgainst"`
    ShotsFromInsideTheBoxAgainst int    `json:"shotsFromInsideTheBoxAgainst"`
    ShotsFromOutsideTheBoxAgainst int   `json:"shotsFromOutsideTheBoxAgainst"`
    ShotsOffTargetAgainst       int     `json:"shotsOffTargetAgainst"`
    ShotsOnTargetAgainst        int     `json:"shotsOnTargetAgainst"`
    BlockedScoringAttemptAgainst int    `json:"blockedScoringAttemptAgainst"`
    TacklesAgainst              int     `json:"tacklesAgainst"`
    TotalFinalThirdPassesAgainst int    `json:"totalFinalThirdPassesAgainst"`
    OppositionHalfPassesTotalAgainst int `json:"oppositionHalfPassesTotalAgainst"`
    OwnHalfPassesTotalAgainst   int     `json:"ownHalfPassesTotalAgainst"`
    TotalPassesAgainst          int     `json:"totalPassesAgainst"`
    YellowCardsAgainst          int     `json:"yellowCardsAgainst"`
    ThrowIns                    int     `json:"throwIns"`
    GoalKicks                   int     `json:"goalKicks"`
    BallRecovery                int     `json:"ballRecovery"`
    FreeKicks                   int     `json:"freeKicks"`
    Matches                     int     `json:"matches"`
    AwardedMatches              int     `json:"awardedMatches"`
}
